import Body from 'react-muscle-highlighter'

// Muscle slugs generated by the LLM (see MUSCLE_GROUPS in backend/src/openai.js)
// already match react-muscle-highlighter's Slug type one-to-one, so no mapping
// step is needed here — just hand the array straight through.
function MuscleDiagram({ muscles = [], sex }) {
  const gender = sex === 'female' ? 'female' : 'male'
  const data = muscles.map((slug) => ({ slug, color: 'var(--accent)' }))

  return (
    <div className="muscle-diagram">
      <Body data={data} side="front" gender={gender} scale={0.75} defaultFill="var(--chip-bg)" border="var(--border)" />
      <Body data={data} side="back" gender={gender} scale={0.75} defaultFill="var(--chip-bg)" border="var(--border)" />
    </div>
  )
}

export default MuscleDiagram
